CREATE TABLE myhomereno_estimates (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    project_id INTEGER
        REFERENCES myhomereno_projects(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    contractor_name TEXT NOT NULL,
    price TEXT NOT NULL,
    details TEXT NOT NULL,
    total_time TEXT NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL
);
